# version of python to be used in docker for maintainability 
version: "3.9"

# services - docker compose files usually include 1 or more services to be used
# app is the name of our service. this is the service that will run the docker file
# build > context specifies that we want to build the docker file inside the cur directory
# args: - DEV=true sets an argument in the build folder w k,v = DEV,true
# ports connects port 8000 from our local machine to port 8000 in docker cointainer. this is how can access network to connect to docker server
# volumes are a way to map our directories in local to the docker container so they're located at same level within their context
# command is the cmd used to run teh service in docker container
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app 
    command: >
      sh -c "py manage.py runserver 0.0.0.0:8000"