# AFTER CREATING THIS FILE, CHECK GITHUB ACTIONS AND REFRESH IT ONCE YOU PUSH CHANGES IT WILL UPDATE
# the --- signifies that this is a yml file to github
---
# name is name that appears in github actions
name: Checks

# on is the trigger, so on git push, run this file's jobs
on: [push]

# jobs indicates the jobs to be run
# test-lint is the id of that specific job, could use job ids to run in specific order
# name is what shows as name in the github actions interface
# runs-on is the OS that we'll run the job on; ubuntu is a basic linux OS
  # ubuntu runner should already come built-in with docker-compose
jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
    # name is the human readable name that appears in github interface
    # uses allows you to use a pre-made action, which in this case is a task that runs in a docker container that logs into dockerhub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # the uses here triggers an action that checks out the code to run next steps
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      # removing Linting since there's a lot of errors based on my code comments
      # - name: Lint
      #   run: docker-compose run --rm app sh -c "flake8"